linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - gocritic
    - unconvert
    - nilerr
    - bodyclose
    - durationcheck
    - prealloc
    - whitespace

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 5
